
//------------------------------------------------------------------------

#include <iostream>

//------------------------------------------------------------------------

int main()
try {

	

}
catch (std::runtime_error e) {
	std::cerr << e.what() << '\n';
}
catch (...) {
	std::cerr << "Default exception...\n";
}

//------------------------------------------------------------------------
